// LIST

export const GET_ARRIVAL_LIST_LOADING = "GET_ARRIVAL_LIST_LOADING";
export const GET_ARRIVAL_LIST = "GET_ARRIVAL_LIST";
export const GET_ARRIVAL_LIST_ERROR = "GET_ARRIVAL_LIST_ERROR";
export const UPDATE_ARRIVAL_LIST_FILTER_PROPS = "UPDATE_ARRIVAL_LIST_FILTER_PROPS";
export const GET_ARRIVAL_LIST_SUPPLIERS_ITEMS_LOADING = "GET_ARRIVAL_LIST_SUPPLIERS_ITEMS_LOADING";
export const GET_ARRIVAL_LIST_SUPPLIERS_ITEMS = "GET_ARRIVAL_LIST_SUPPLIERS_ITEMS";
export const GET_ARRIVAL_LIST_SUPPLIERS_ITEMS_ERROR = "GET_ARRIVAL_LIST_SUPPLIERS_ITEMS_ERROR";

// CREATE

export const UPDATE_ARRIVAL_CREATE_FORM_FIELDS = "UPDATE_ARRIVAL_CREATE_FORM_FIELDS";
export const RESET_ARRIVAL_CREATE_FORM_FIELDS = "RESET_ARRIVAL_CREATE_FORM_FIELDS";

export const GET_ARRIVAL_CREATE_BRANCHES_ITEMS_LOADING = "GET_ARRIVAL_CREATE_BRANCHES_ITEMS_LOADING";
export const GET_ARRIVAL_CREATE_BRANCHES_ITEMS = "GET_ARRIVAL_CREATE_BRANCHES_ITEMS";
export const GET_ARRIVAL_CREATE_BRANCHES_ITEMS_ERROR = "GET_ARRIVAL_CREATE_BRANCHES_ITEMS_ERROR";
export const GET_ARRIVAL_CREATE_SUPPLIERS_ITEMS_LOADING = "GET_ARRIVAL_CREATE_SUPPLIERS_ITEMS_LOADING";
export const GET_ARRIVAL_CREATE_SUPPLIERS_ITEMS = "GET_ARRIVAL_CREATE_SUPPLIERS_ITEMS";
export const GET_ARRIVAL_CREATE_SUPPLIERS_ITEMS_ERROR = "GET_ARRIVAL_CREATE_SUPPLIERS_ITEMS_ERROR";
export const GET_ARRIVAL_CREATE_ORDER_DETAILS_LOADING = "GET_ARRIVAL_CREATE_ORDER_DETAILS_LOADING";
export const GET_ARRIVAL_CREATE_ORDER_DETAILS = "GET_ARRIVAL_CREATE_ORDER_DETAILS";
export const GET_ARRIVAL_CREATE_ORDER_DETAILS_ERROR = "GET_ARRIVAL_CREATE_ORDER_DETAILS_ERROR";
export const RESET_ARRIVAL_CREATE_ORDER_DETAILS = "RESET_ARRIVAL_CREATE_ORDER_DETAILS";
export const GET_ARRIVAL_CREATE_ORDERS_ITEMS_LOADING = "GET_ARRIVAL_CREATE_ORDERS_ITEMS_LOADING";
export const GET_ARRIVAL_CREATE_ORDERS_ITEMS = "GET_ARRIVAL_CREATE_ORDERS_ITEMS";
export const GET_ARRIVAL_CREATE_ORDERS_ITEMS_ERROR = "GET_ARRIVAL_CREATE_ORDERS_ITEMS_ERROR";
export const GET_ARRIVAL_CREATE_PRODUCTS_ITEMS_LOADING = "GET_ARRIVAL_CREATE_PRODUCTS_ITEMS_LOADING";
export const GET_ARRIVAL_CREATE_PRODUCTS_ITEMS = "GET_ARRIVAL_CREATE_PRODUCTS_ITEMS";
export const GET_ARRIVAL_CREATE_PRODUCTS_ITEMS_ERROR = "GET_ARRIVAL_CREATE_PRODUCTS_ITEMS_ERROR";
export const GET_ARRIVAL_CREATE_PRODUCT_UNITS_LOADING = "GET_ARRIVAL_CREATE_PRODUCT_UNITS_LOADING";
export const GET_ARRIVAL_CREATE_PRODUCT_UNITS = "GET_ARRIVAL_CREATE_PRODUCT_UNITS";
export const GET_ARRIVAL_CREATE_PRODUCT_UNITS_ERROR = "GET_ARRIVAL_CREATE_PRODUCT_UNITS_ERROR";
export const RESET_ARRIVAL_CREATE_PRODUCT_UNITS = "RESET_ARRIVAL_CREATE_PRODUCT_UNITS";
export const ADD_ARRIVALS_BY_ORDER_LOADING = "ADD_ARRIVALS_BY_ORDER_LOADING";
export const ADD_ARRIVALS_BY_ORDER = "ADD_ARRIVALS_BY_ORDER";
export const ADD_ARRIVALS_BY_ORDER_ERROR = "ADD_ARRIVALS_BY_ORDER_ERROR";
export const ADD_ARRIVALS_BY_PRODUCT_LOADING = "ADD_ARRIVALS_BY_PRODUCT_LOADING";
export const ADD_ARRIVALS_BY_PRODUCT = "ADD_ARRIVALS_BY_PRODUCT";
export const ADD_ARRIVALS_BY_PRODUCT_ERROR = "ADD_ARRIVALS_BY_PRODUCT_ERROR";
export const RESET_ADD_ARRIVALS = "RESET_ADD_ARRIVALS";
export const RESET_ARRIVAL_CREATE = "RESET_ARRIVAL_CREATE";

// INFO
export const GET_ARRIVAL_INFO_LOADING = "GET_ARRIVAL_INFO_LOADING";
export const GET_ARRIVAL_INFO = "GET_ARRIVAL_INFO";
export const GET_ARRIVAL_INFO_ERROR = "GET_ARRIVAL_INFO_ERROR";
export const RESET_ARRIVAL_INFO = "RESET_ARRIVAL_INFO";