export const GET_ORDERS_LIST_LOADING = "GET_ORDERS_LIST_LOADING";
export const GET_ORDERS_LIST = "GET_ORDERS_LIST";
export const GET_ORDERS_LIST_ERROR = "GET_ORDERS_LIST_ERROR";

export const UPDATE_ORDERS_LIST_FILTER_PROPS = "UPDATE_ORDERS_LIST_FILTER_PROPS";

export const SYNC_INVOICES_LOADING = "SYNC_INVOICES_LOADING";
export const SYNC_INVOICES = "SYNC_INVOICES";
export const SYNC_INVOICES_ERROR = "SYNC_INVOICES_ERROR";
export const RESET_SYNC_INVOICES = "RESET_SYNC_INVOICES";

export const DOWNLOAD_XLS_LOADING = "DOWNLOAD_XLS_LOADING";
export const DOWNLOAD_XLS = "DOWNLOAD_XLS";
export const DOWNLOAD_XLS_ERROR = "DOWNLOAD_XLS_ERROR";
export const RESET_DOWNLOAD_XLS = "RESET_DOWNLOAD_XLS";

export const GET_ORDER_STATUSES = "GET_ORDER_STATUSES";
export const GET_ORDER_STATUSES_ERROR = "GET_ORDER_STATUSES_ERROR";

export const GET_ORDER_SUB_STATUSES = "GET_ORDER_SUB_STATUSES";
export const GET_ORDER_SUB_STATUSES_ERROR = "GET_ORDER_SUB_STATUSES_ERROR";
export const RESET_ORDER_SUB_STATUSES = "RESET_ORDER_SUB_STATUSES";

export const GET_SUPPLIERS_ITEMS_LOADING = "GET_SUPPLIERS_ITEMS_LOADING";
export const GET_SUPPLIERS_ITEMS = "GET_SUPPLIERS_ITEMS";
export const GET_SUPPLIERS_ITEMS_ERROR = "GET_SUPPLIERS_ITEMS_ERROR";

export const GET_ORDER_DETAILS_LOADING = "GET_ORDER_DETAILS_LOADING";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";
export const GET_ORDER_DETAILS_ERROR = "GET_ORDER_DETAILS_ERROR";
export const RESET_ORDER_DETAILS = "RESET_ORDER_DETAILS";

export const CONFIRM_ORDER_LOADING = "CONFIRM_ORDER_LOADING";
export const CONFIRM_ORDER = "CONFIRM_ORDER";
export const CONFIRM_ORDER_ERROR = "CONFIRM_ORDER_ERROR";
export const RESET_CONFIRM_ORDER = "RESET_CONFIRM_ORDER";

export const REJECT_ORDER_LOADING = "REJECT_ORDER_LOADING";
export const REJECT_ORDER = "REJECT_ORDER";
export const REJECT_ORDER_ERROR = "REJECT_ORDER_ERROR";
export const RESET_REJECT_ORDER = "RESET_REJECT_ORDER";

export const GET_CONTRACT_DETAILS_LOADING = "GET_CONTRACT_DETAILS_LOADING";
export const GET_CONTRACT_DETAILS = "GET_CONTRACT_DETAILS";
export const GET_CONTRACT_DETAILS_ERROR = "GET_CONTRACT_DETAILS_ERROR";

export const CONFIRM_CONTRACT_LOADING = "CONFIRM_CONTRACT_LOADING";
export const CONFIRM_CONTRACT = "CONFIRM_CONTRACT";
export const CONFIRM_CONTRACT_ERROR = "CONFIRM_CONTRACT_ERROR";
export const RESET_CONFIRM_CONTRACT = "RESET_CONFIRM_CONTRACT";

export const REJECT_CONTRACT_LOADING = "REJECT_CONTRACT_LOADING";
export const REJECT_CONTRACT = "REJECT_CONTRACT";
export const REJECT_CONTRACT_ERROR = "REJECT_CONTRACT_ERROR";
export const RESET_REJECT_CONTRACT = "RESET_REJECT_CONTRACT";

export const EXPIRED_CONTRACT_LOADING = "EXPIRED_CONTRACT_LOADING";
export const EXPIRED_CONTRACT = "EXPIRED_CONTRACT";
export const EXPIRED_CONTRACT_ERROR = "EXPIRED_CONTRACT_ERROR";
export const RESET_EXPIRED_CONTRACT = "RESET_EXPIRED_CONTRACT";

export const GET_INVOICE_PAYMENT_DETAILS_LOADING = "GET_INVOICE_PAYMENT_DETAILS_LOADING";
export const GET_INVOICE_PAYMENT_DETAILS = "GET_INVOICE_PAYMENT_DETAILS";
export const GET_INVOICE_PAYMENT_DETAILS_ERROR = "GET_INVOICE_PAYMENT_DETAILS_ERROR";

export const CONFIRM_INVOICE_PAYMENT_LOADING = "CONFIRM_INVOICE_PAYMENT_LOADING";
export const CONFIRM_INVOICE_PAYMENT = "CONFIRM_INVOICE_PAYMENT";
export const CONFIRM_INVOICE_PAYMENT_ERROR = "CONFIRM_INVOICE_PAYMENT_ERROR";
export const RESET_CONFIRM_INVOICE_PAYMENT = "RESET_CONFIRM_INVOICE_PAYMENT";

export const GET_POWER_OF_ATTORNEY_DETAILS_LOADING = "GET_POWER_OF_ATTORNEY_DETAILS_LOADING";
export const GET_POWER_OF_ATTORNEY_DETAILS = "GET_POWER_OF_ATTORNEY_DETAILS";
export const GET_POWER_OF_ATTORNEY_DETAILS_ERROR = "GET_POWER_OF_ATTORNEY_DETAILS_ERROR";

export const GET_CURRENT_RESPONSIBLE_PERSON_ITEMS = "GET_CURRENT_RESPONSIBLE_PERSON_ITEMS";

export const CREATE_POWER_OF_ATTORNEY_LOADING = "CREATE_POWER_OF_ATTORNEY_LOADING";
export const CREATE_POWER_OF_ATTORNEY = "CREATE_POWER_OF_ATTORNEY";
export const CREATE_POWER_OF_ATTORNEY_ERROR = "CREATE_POWER_OF_ATTORNEY_ERROR";
export const RESET_CREATE_POWER_OF_ATTORNEY = "RESET_CREATE_POWER_OF_ATTORNEY";

export const RECEIVE_ORDER_LOADING = "RECEIVE_ORDER_LOADING";
export const RECEIVE_ORDER = "RECEIVE_ORDER";
export const RECEIVE_ORDER_ERROR = "RECEIVE_ORDER_ERROR";
export const RESET_RECEIVE_ORDER = "RESET_RECEIVE_ORDER";

export const GET_INVOICE_DETAILS_LOADING = "GET_INVOICE_DETAILS_LOADING";
export const GET_INVOICE_DETAILS = "GET_INVOICE_DETAILS";
export const GET_INVOICE_DETAILS_ERROR = "GET_INVOICE_DETAILS_ERROR";

export const CHECK_INVOICE_STATUS_LOADING = "CHECK_INVOICE_STATUS_LOADING";
export const CHECK_INVOICE_STATUS = "CHECK_INVOICE_STATUS";
export const CHECK_INVOICE_STATUS_ERROR = "CHECK_INVOICE_STATUS_ERROR";
export const RESET_CHECK_INVOICE_STATUS = "RESET_CHECK_INVOICE_STATUS";