export const GET_OFFERS_LIST = "GET_OFFERS_LIST";
export const GET_OFFERS_LIST_LOADING = "GET_OFFERS_LIST_LOADING";
export const GET_OFFERS_LIST_ERROR = "GET_OFFERS_LIST_ERROR";

export const UPDATE_OFFERS_LIST_FILTER_PROPS = "UPDATE_OFFERS_LIST_FILTER_PROPS";
export const RESET_OFFERS_LIST_FILTER_PROPS = "RESET_OFFERS_LIST_FILTER_PROPS";
export const RESET_SUPPLIER_CATALOG = "RESET_SUPPLIER_CATALOG";

export const GET_VAT_ITEMS_LOADING = "GET_VAT_ITEMS_LOADING";
export const GET_VAT_ITEMS = "GET_VAT_ITEMS";
export const GET_VAT_ITEMS_ERROR = "GET_VAT_ITEMS_ERROR";