export const cardTypesCodes = {
  CUMULATIVE: "CUMULATIVE",
  DISCOUNT: "DISCOUNT",
  CREDIT: "CREDIT"
};

export const systemsStatuses = {
  ACCEPTED: "ACCEPTED",
  ACTIVE: "ACTIVE",
  PAUSE: "PAUSE",
  INACTIVE: "INACTIVE"
};

export const GET_LOYALTY_CARD_TYPES = "GET_LOYALTY_CARD_TYPES";
export const GET_LOYALTY_CARD_TYPES_SUCCESS = "GET_LOYALTY_CARD_TYPES_SUCCESS";
export const GET_LOYALTY_CARD_TYPES_ERROR = "GET_LOYALTY_CARD_TYPES_ERROR";

export const GET_LOYALTY_PERIODS = "GET_LOYALTY_PERIODS";
export const GET_LOYALTY_PERIODS_SUCCESS = "GET_LOYALTY_PERIODS_SUCCESS";
export const GET_LOYALTY_PERIODS_ERROR = "GET_LOYALTY_PERIODS_ERROR";

export const GET_LOYALTY_SYSTEM_STATUSES = "GET_LOYALTY_SYSTEM_STATUSES";
export const GET_LOYALTY_SYSTEM_STATUSES_SUCCESS = "GET_LOYALTY_SYSTEM_STATUSES_SUCCESS";
export const GET_LOYALTY_SYSTEM_STATUSES_ERROR = "GET_LOYALTY_SYSTEM_STATUSES_ERROR";

export const GET_LOYALTY_SYSTEMS_ITEMS = "GET_LOYALTY_SYSTEMS_ITEMS";
export const GET_LOYALTY_SYSTEMS_ITEMS_SUCCESS = "GET_LOYALTY_SYSTEMS_ITEMS_SUCCESS";
export const GET_LOYALTY_SYSTEMS_ITEMS_ERROR = "GET_LOYALTY_SYSTEMS_ITEMS_ERROR";

export const GET_LOYALTY_CARDS = "GET_LOYALTY_CARDS";
export const GET_LOYALTY_CARDS_SUCCESS = "GET_LOYALTY_CARDS_SUCCESS";
export const GET_LOYALTY_CARDS_ERROR = "GET_LOYALTY_CARDS_ERROR";

export const UPDATE_LOYALTY_CARDS_FILTER = "UPDATE_LOYALTY_CARDS_FILTER";
export const RESET_LOYALTY_CARDS_FILTER = "RESET_LOYALTY_CARDS_FILTER";

export const GET_LOYALTY_CARDS_STATS = "GET_LOYALTY_CARDS_STATS";
export const GET_LOYALTY_CARDS_STATS_SUCCESS = "GET_LOYALTY_CARDS_STATS_SUCCESS";
export const GET_LOYALTY_CARDS_STATS_ERROR = "GET_LOYALTY_CARDS_STATS_ERROR";

export const GET_LOYALTY_CARD_DETAILS = "GET_LOYALTY_CARD_DETAILS";
export const GET_LOYALTY_CARD_DETAILS_SUCCESS = "GET_LOYALTY_CARD_DETAILS_SUCCESS";
export const GET_LOYALTY_CARD_DETAILS_ERROR = "GET_LOYALTY_CARD_DETAILS_ERROR";
export const RESET_LOYALTY_CARD_DETAILS = "RESET_LOYALTY_CARD_DETAILS";

export const ADD_LOYALTY_CARD = "ADD_LOYALTY_CARD";
export const ADD_LOYALTY_CARD_SUCCESS = "ADD_LOYALTY_CARD_SUCCESS";
export const ADD_LOYALTY_CARD_ERROR = "ADD_LOYALTY_CARD_ERROR";
export const RESET_ADD_LOYALTY_CARD = "RESET_ADD_LOYALTY_CARD";

export const UPDATE_LOYALTY_CARD = "UPDATE_LOYALTY_CARD";
export const UPDATE_LOYALTY_CARD_SUCCESS = "UPDATE_LOYALTY_CARD_SUCCESS";
export const UPDATE_LOYALTY_CARD_ERROR = "UPDATE_LOYALTY_CARD_ERROR";
export const RESET_UPDATE_LOYALTY_CARD = "RESET_UPDATE_LOYALTY_CARD";

export const DELETE_LOYALTY_CARD = "DELETE_LOYALTY_CARD";
export const DELETE_LOYALTY_CARD_SUCCESS = "DELETE_LOYALTY_CARD_SUCCESS";
export const DELETE_LOYALTY_CARD_ERROR = "DELETE_LOYALTY_CARD_ERROR";
export const RESET_DELETE_LOYALTY_CARD_ERROR = "RESET_DELETE_LOYALTY_CARD_ERROR";


export const GET_LOYALTY_SYSTEMS = "GET_LOYALTY_SYSTEMS";
export const GET_LOYALTY_SYSTEMS_SUCCESS = "GET_LOYALTY_SYSTEMS_SUCCESS";
export const GET_LOYALTY_SYSTEMS_ERROR = "GET_LOYALTY_SYSTEMS_ERROR";

export const UPDATE_LOYALTY_SYSTEMS_FILTER = "UPDATE_LOYALTY_SYSTEMS_FILTER";
export const RESET_LOYALTY_SYSTEMS_FILTER = "RESET_LOYALTY_SYSTEMS_FILTER";

export const CHANGE_LOYALTY_SYSTEM_STATUS = "CHANGE_LOYALTY_SYSTEM_STATUS";
export const CHANGE_LOYALTY_SYSTEM_STATUS_SUCCESS = "CHANGE_LOYALTY_SYSTEM_STATUS_SUCCESS";
export const CHANGE_LOYALTY_SYSTEM_STATUS_ERROR = "CHANGE_LOYALTY_SYSTEM_STATUS_ERROR";
export const RESET_CHANGE_LOYALTY_SYSTEM_STATUS = "RESET_CHANGE_LOYALTY_SYSTEM_STATUS";

export const GET_LOYALTY_SYSTEM_DETAILS = "GET_LOYALTY_SYSTEM_DETAILS";
export const GET_LOYALTY_SYSTEM_DETAILS_SUCCESS = "GET_LOYALTY_SYSTEM_DETAILS_SUCCESS";
export const GET_LOYALTY_SYSTEM_DETAILS_ERROR = "GET_LOYALTY_SYSTEM_DETAILS_ERROR";
export const RESET_LOYALTY_SYSTEM_DETAILS = "RESET_LOYALTY_SYSTEM_DETAILS";


export const GET_ADD_LOYALTY_SYSTEM_CARDS = "GET_ADD_LOYALTY_SYSTEM_CARDS";
export const GET_ADD_LOYALTY_SYSTEM_CARDS_SUCCESS = "GET_ADD_LOYALTY_SYSTEM_CARDS_SUCCESS";
export const GET_ADD_LOYALTY_SYSTEM_CARDS_ERROR = "GET_ADD_LOYALTY_SYSTEM_CARDS_ERROR";

export const GET_ADD_LOYALTY_SYSTEM_BRANCHES = "GET_ADD_LOYALTY_SYSTEM_BRANCHES";
export const GET_ADD_LOYALTY_SYSTEM_BRANCHES_SUCCESS = "GET_ADD_LOYALTY_SYSTEM_BRANCHES_SUCCESS";
export const GET_ADD_LOYALTY_SYSTEM_BRANCHES_ERROR = "GET_ADD_LOYALTY_SYSTEM_BRANCHES_ERROR";


export const ADD_LOYALTY_SYSTEM = "ADD_LOYALTY_SYSTEM";
export const ADD_LOYALTY_SYSTEM_SUCCESS = "ADD_LOYALTY_SYSTEM_SUCCESS";
export const ADD_LOYALTY_SYSTEM_ERROR = "ADD_LOYALTY_SYSTEM_ERROR";
export const RESET_ADD_LOYALTY_SYSTEM = "RESET_ADD_LOYALTY_SYSTEM";

export const UPDATE_LOYALTY_SYSTEM = "UPDATE_LOYALTY_SYSTEM";
export const UPDATE_LOYALTY_SYSTEM_SUCCESS = "UPDATE_LOYALTY_SYSTEM_SUCCESS";
export const UPDATE_LOYALTY_SYSTEM_ERROR = "UPDATE_LOYALTY_SYSTEM_ERROR";
export const RESET_UPDATE_LOYALTY_SYSTEM = "RESET_UPDATE_LOYALTY_SYSTEM";

export const GET_LOYALTY_CLIENTS = "GET_LOYALTY_CLIENTS";
export const GET_LOYALTY_CLIENTS_SUCCESS = "GET_LOYALTY_CLIENTS_SUCCESS";
export const GET_LOYALTY_CLIENTS_ERROR = "GET_LOYALTY_CLIENTS_ERROR";

export const UPDATE_LOYALTY_CLIENTS_FILTER = "UPDATE_LOYALTY_CLIENTS_FILTER";
export const RESET_LOYALTY_CLIENTS_FILTER = "RESET_LOYALTY_CLIENTS_FILTER";

export const GET_A_PAY_USER_DETAILS = "GET_A_PAY_USER_DETAILS";
export const GET_A_PAY_USER_DETAILS_SUCCESS = "GET_A_PAY_USER_DETAILS_SUCCESS";
export const GET_A_PAY_USER_DETAILS_ERROR = "GET_A_PAY_USER_DETAILS_ERROR";
export const RESET_A_PAY_USER_DETAILS = "GET_A_PAY_USER_DETAILS_SUCCESS";

export const GET_LOYALTY_CLIENT_LEVELS = "GET_LOYALTY_CLIENT_LEVELS";
export const GET_LOYALTY_CLIENT_LEVELS_SUCCESS = "GET_LOYALTY_CLIENT_LEVELS_SUCCESS";
export const GET_LOYALTY_CLIENT_LEVELS_ERROR = "GET_LOYALTY_CLIENT_LEVELS_ERROR";
export const RESET_LOYALTY_CLIENT_LEVELS = "RESET_LOYALTY_CLIENT_LEVELS";

export const ADD_LOYALTY_CLIENT = "ADD_LOYALTY_CLIENT";
export const ADD_LOYALTY_CLIENT_SUCCESS = "ADD_LOYALTY_CLIENT_SUCCESS";
export const ADD_LOYALTY_CLIENT_ERROR = "ADD_LOYALTY_CLIENT_ERROR";
export const RESET_ADD_LOYALTY_CLIENT = "RESET_ADD_LOYALTY_CLIENT";