export const ADD_ORDERING_PRODUCT = "ADD_ORDERING_PRODUCT";
export const UPDATE_ORDERING_PRODUCT = "UPDATE_ORDERING_PRODUCT";
export const DELETE_ORDERING_PRODUCT = "DELETE_ORDERING_PRODUCT";
export const RESET_ORDERING = "RESET_ORDERING";
export const SET_ORDERING_FIELDS = "SET_ORDERING_FIELDS";
export const SET_EDITING_PRODUCTS = "SET_EDITING_PRODUCTS";

export const GET_SUPPLIERS_ITEMS = "GET_SUPPLIERS_ITEMS";
export const GET_SUPPLIERS_ITEMS_LOADING = "GET_SUPPLIERS_ITEMS_LOADING";
export const GET_SUPPLIERS_ITEMS_ERROR = "GET_SUPPLIERS_ITEMS_ERROR";

export const GET_BRANCHES_ITEMS_LOADING = "GET_BRANCHES_ITEMS_LOADING";
export const GET_BRANCHES_ITEMS = "GET_BRANCHES_ITEMS";
export const GET_BRANCHES_ITEMS_ERROR = "GET_BRANCHES_ITEMS_ERROR";

export const GET_PAYMENTS_ITEMS = "GET_PAYMENTS_ITEMS";

export const GET_DELIVERY_TYPE_ITEMS = "GET_DELIVERY_TYPE_ITEMS";

export const GET_PRODUCTS_ITEMS_LOADING = "GET_ADD_PRODUCTS_ITEMS_LOADING";
export const GET_PRODUCTS_ITEMS = "GET_ADD_PRODUCTS_ITEMS";
export const GET_PRODUCTS_ITEMS_ERROR = "GET_ADD_PRODUCTS_ITEMS_ERROR";
export const RESET_PRODUCTS_ITEMS = "RESET_PRODUCTS_ITEMS";

export const CREATE_ORDER_LOADING = "CREATE_ORDER_LOADING";
export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const UPDATE_ORDER_LOADING = "UPDATE_ORDER_LOADING";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";

export const DELETE_DRAFT_ORDER_LOADING = "DELETE_DRAFT_ORDER_LOADING";
export const DELETE_DRAFT_ORDER = "DELETE_DRAFT_ORDER";
export const DELETE_DRAFT_ORDER_ERROR = "DELETE_DRAFT_ORDER_ERROR";
export const RESET_DELETE_DRAFT_ORDER = "RESET_DELETE_DRAFT_ORDER";

export const NEW = "NEW";
export const DRAFT = "DRAFT";
export const REVISED_BY_SUPPLIER = "REVISED_BY_SUPPLIER";
export const REVISED_BY_CLIENT = "REVISED_BY_CLIENT";