export const GET_SUPPLIER_INFO_LOADING = "GET_SUPPLIER_INFO_LOADING";
export const GET_SUPPLIER_INFO = "GET_SUPPLIER_INFO";
export const GET_SUPPLIER_INFO_ERROR = "GET_SUPPLIER_INFO_ERROR";

export const GET_CATEGORIES_LIST_LOADING = "GET_CATEGORIES_LIST_LOADING";
export const GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST";
export const GET_CATEGORIES_LIST_ERROR = "GET_CATEGORIES_LIST_ERROR";
export const RESET_CATEGORIES_LIST = "RESET_CATEGORIES_LIST";

export const RESET_SUPPLIER_DETAIL = "RESET_SUPPLIER_DETAIL";

export const SET_CATEGORIES_BRANCH = "SET_CATEGORIES_BRANCH";

export const GET_BRANCHES_ITEMS_LOADING = "GET_BRANCHES_ITEMS_LOADING";
export const GET_BRANCHES_ITEMS = "GET_BRANCHES_ITEMS";
export const GET_BRANCHES_ITEMS_ERROR = "GET_BRANCHES_ITEMS_ERROR";

export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const RESET_PRODUCTS = "RESET_PRODUCTS";

export const UPDATE_PRODUCTS_FILTER_PROPS = "UPDATE_PRODUCTS_FILTER_PROPS";

export const ADD_SELECTED_PRODUCT = "ADD_SELECTED_PRODUCT";
export const SHOW_SELECTED_PRODUCTS = "SHOW_SELECTED_PRODUCTS";