export const DATA_ENTRY = "DATA_ENTRY";

export const GET_SERVICE_BRANCHES_ITEMS = "GET_SERVICE_BRANCHES_ITEMS";
export const GET_SERVICE_BRANCHES_ITEMS_SUCCESS = "GET_SERVICE_BRANCHES_ITEMS_SUCCESS";
export const GET_SERVICE_BRANCHES_ITEMS_ERROR = "GET_SERVICE_BRANCHES_ITEMS_ERROR";

export const GET_SERVICE_AGREEMENTS_LIST = "GET_SERVICE_AGREEMENTS_LIST";
export const GET_SERVICE_AGREEMENTS_LIST_SUCCESS = "GET_SERVICE_AGREEMENTS_LIST_SUCCESS";
export const GET_SERVICE_AGREEMENTS_LIST_ERROR = "GET_SERVICE_AGREEMENTS_LIST_ERROR";

export const UPDATE_SERVICE_AGREEMENTS_LIST_FILTER = "UPDATE_SERVICE_AGREEMENTS_LIST_FILTER";
export const RESET_SERVICE_AGREEMENTS_LIST_FILTER = "RESET_SERVICE_AGREEMENTS_LIST_FILTER";

export const GET_SERVICES_TARIFFS = "GET_SERVICES_TARIFFS";
export const GET_SERVICES_TARIFFS_SUCCESS = "GET_SERVICES_TARIFFS_SUCCESS";
export const GET_SERVICES_TARIFFS_ERROR = "GET_SERVICES_TARIFFS_ERROR";

export const GET_BRANCHES_COUNT = "GET_BRANCHES_COUNT";
export const GET_BRANCHES_COUNT_SUCCESS = "GET_BRANCHES_COUNT_SUCCESS";
export const GET_BRANCHES_COUNT_ERROR = "GET_BRANCHES_COUNT_ERROR";

export const GET_CUSTOMER_PUBLIC_OFFER = "GET_CUSTOMER_PUBLIC_OFFER";
export const GET_CUSTOMER_PUBLIC_OFFER_SUCCESS = "GET_CUSTOMER_PUBLIC_OFFER_SUCCESS";
export const GET_CUSTOMER_PUBLIC_OFFER_ERROR = "GET_CUSTOMER_PUBLIC_OFFER_ERROR";
export const RESET_CUSTOMER_PUBLIC_OFFER = "RESET_CUSTOMER_PUBLIC_OFFER";

export const GET_LAST_PUBLIC_OFFER = "GET_LAST_PUBLIC_OFFER";
export const GET_LAST_PUBLIC_OFFER_SUCCESS = "GET_LAST_PUBLIC_OFFER_SUCCESS";
export const GET_LAST_PUBLIC_OFFER_ERROR = "GET_LAST_PUBLIC_OFFER_ERROR";

export const ACCEPT_PUBLIC_OFFER = "ACCEPT_PUBLIC_OFFER";
export const ACCEPT_PUBLIC_OFFER_SUCCESS = "ACCEPT_PUBLIC_OFFER_SUCCESS";
export const ACCEPT_PUBLIC_OFFER_ERROR = "ACCEPT_PUBLIC_OFFER_ERROR";
export const RESET_ACCEPT_PUBLIC_OFFER = "RESET_ACCEPT_PUBLIC_OFFER";

export const CREATE_SUBSCRIBE_AGREEMENT = "CREATE_SUBSCRIBE_AGREEMENT";
export const CREATE_SUBSCRIBE_AGREEMENT_SUCCESS = "CREATE_SUBSCRIBE_AGREEMENT_SUCCESS";
export const CREATE_SUBSCRIBE_AGREEMENT_ERROR = "CREATE_SUBSCRIBE_AGREEMENT_ERROR";
export const RESET_CREATE_SUBSCRIBE_AGREEMENT = "RESET_CREATE_SUBSCRIBE_AGREEMENT";

export const CREATE_CUSTOM_AGREEMENT = "CREATE_CUSTOM_AGREEMENT";
export const CREATE_CUSTOM_AGREEMENT_SUCCESS = "CREATE_CUSTOM_AGREEMENT_SUCCESS";
export const CREATE_CUSTOM_AGREEMENT_ERROR = "CREATE_CUSTOM_AGREEMENT_ERROR";
export const RESET_CREATE_CUSTOM_AGREEMENT = "RESET_CREATE_CUSTOM_AGREEMENT";

export const GET_SERVICE_AGREEMENT_DETAILS = "GET_SERVICE_AGREEMENT_DETAILS";
export const GET_SERVICE_AGREEMENT_DETAILS_SUCCESS = "GET_SERVICE_AGREEMENT_DETAILS_SUCCESS";
export const GET_SERVICE_AGREEMENT_DETAILS_ERROR = "GET_SERVICE_AGREEMENT_DETAILS_ERROR";
export const RESET_SERVICE_AGREEMENT_DETAILS = "RESET_SERVICE_AGREEMENT_DETAILS";

export const UPDATE_AGREEMENT_SERVICE_DESC = "UPDATE_AGREEMENT_SERVICE_DESC";
export const UPDATE_AGREEMENT_SERVICE_DESC_SUCCESS = "UPDATE_AGREEMENT_SERVICE_DESC_SUCCESS";
export const UPDATE_AGREEMENT_SERVICE_DESC_ERROR = "UPDATE_AGREEMENT_SERVICE_DESC_ERROR";
export const RESET_UPDATE_AGREEMENT_SERVICE_DESC = "RESET_UPDATE_AGREEMENT_SERVICE_DESC";

export const UPLOAD_AGREEMENT_FILE = "UPLOAD_AGREEMENT_FILE";
export const UPLOAD_AGREEMENT_FILE_SUCCESS = "UPLOAD_AGREEMENT_FILE_SUCCESS";
export const UPLOAD_AGREEMENT_FILE_ERROR = "UPLOAD_AGREEMENT_FILE_ERROR";
export const RESET_UPLOAD_AGREEMENT_FILE = "RESET_UPLOAD_AGREEMENT_FILE";